language: go
go:
- 1.13.x
script:
- go test -v -race ./...

before_script:
- echo "REPO $TRAVIS_REPO_SLUG TAG ${TRAVIS_TAG}"

deploy:
  - #goreleaser
    provider: script
    script: curl -sL https://git.io/goreleaser | bash
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux

after_deploy:
  - git clone https://github.com/sensu/sensu-go-bonsai-asset.git bonsai
  - bonsai/generate-sha512sum.sh
  - bonsai/github-release-upload.sh github_api_token=$GITHUB_TOKEN repo_slug="$TRAVIS_REPO_SLUG" tag="${TRAVIS_TAG}" filename="dist/$(cat dist/sha512_file)"

env:
  global:
    secure: TQfagK1hb9XcEJOIv3IJMs9HaQtIWqFrXAhqYpMtyyLdwgrRsYSoUzeBWkdFhhxSN6D91r66GFUxDoGcWPdTMYXaWScQiNzYofq+i1UpL8KLnG4BNhNc9RfgRmIz7W+6YGuk0IThvuI7XO2sDbhM1BwPy+1/3lTMPDr752BuyR7GBEkblJ2Xej6Vf8C+39g5UT2xOfZGehid2KOJvePBoXn/CdiVfzCqQI9CHUrGUiXuMz5O1IPFaqHktsR6RXLy+0OlHyiNcdKDiPHI3u9TBUZUZzIYqeOUqYr6aZXVji3gCZZweuwW/TMgYr7w7IrLeKj3AEWVaD4m1usSD4cxf0cTTnkb3thljTAMabcpBFxoYZJK2wfetJIVzFmWh++kJ1vk01M95kkQrYRBI/Ai0VAhT7CZcMqhxO9OLj8pl038gkvmBlXASf4/38Df3id7RPD4I92SSr8Qf3c04uj4i9NiCOwdPB7VWIvMVwekRjsSLMATqA8972pfw5pBlxp3P9e6QujwiEYQt564NBVSoliomCXfdLZU+NcO/5lIQNMeby76AYeF2PRNdtJ36aW0nz3LxsSdtU7tke3v9Tx1ZlaNpb8qFiaOh4g3HUldgPdYJK6iYM2xAB3FLxqJ7FYuTqyfW42692ncu0GnCO3ApJrCOCU1nmTC9U7LvayacWo=
